services:
  - mysql
rvm:
  - 2.0.0
  - 2.1.*
  - 2.2.*
gemfile:
  - Gemfile
env:
  - RAILS_ENV=test
bundler_args: --without development --path vendor/bundle
script: 
  - bundle exec rake --trace db:create db:migrate
  - bundle exec rspec 
